---
- name: Update and Upgrade Playbook
  hosts: all
  become: true  # Run tasks with elevated privileges

  tasks:
    - name: Update package cache and install 'astra-update'
      apt:
        update_cache: true
        name: astra-update
        state: present

    - name: Perform a full upgrade using custom module
      astra_update:
        upgrade: full
        check_install_disk: false
        use_current_sources_list: true
      diff: true  # Show changes made by this task
